using System.Diagnostics;
using System.ServiceProcess;
using System.Text.Json;
using System.Xml.Linq;
using WEDM.Domain.Enums;
using WEDM.Domain.Interfaces;
using WEDM.Domain.Models;
using WEDM.Engine.Automation;
using WEDM.Engine.Discovery.Parsers;
using WEDM.Engine.Execution;
using WEDM.Engine.ResponseFiles;
using WEDM.Engine.Wlst;
using WEDM.Infrastructure.Registry;

namespace WEDM.Engine.Workflow.Steps;

/// <summary>
/// Runs WLST offline to materialise the domain on disk.
///
/// Implementation note — why we bypass PowerShell
/// ────────────────────────────────────────────────
/// Using Start-Process -Wait -NoNewWindow inside an in-process PS SDK runspace
/// causes a deterministic deadlock in a WPF host process (which has no console):
///
///   WPF process (no console)
///     └── PS RunspacePool thread
///           └── Start-Process wlst.cmd -Wait -NoNewWindow
///                 └── wlst.cmd  ← inherits NULL stdout handle from WPF
///                       └── java.exe (WLST)  ← writes to NULL handle → hangs
///
/// We instead invoke cmd.exe /c wlst.cmd directly via ExternalProcessRunner, which:
///   • Redirects stdout/stderr into async event-driven pipe readers (no buffer fill)
///   • Applies ORACLE_HOME / JAVA_HOME / PATH via ProcessStartInfo.Environment
///   • Adds a watchdog that fires if no output is seen for SilentProcessTimeout
///   • Verifies that java.exe actually spawned within LaunchVerificationTimeout
///   • Kills the full process tree (cmd → wlst.cmd → java) on cancellation or abort
///
/// Script generation
/// ─────────────────
/// Scripts are generated by <see cref="WlstDomainScriptProviderFactory"/> which selects
/// the correct <see cref="IWlstDomainScriptProvider"/> for the target WebLogic version.
/// The key correctness rule: WebLogic 12c/14c/15c require the admin password to be set
/// via <c>cmo.setPassword()</c> on the security-realm MBean — NOT via <c>set('Password',...)</c>
/// which was silently rejected in WLS 12c's <c>writeDomain() → checkSecurityInfo()</c> path.
///
/// Pre-execution validation
/// ────────────────────────
/// <see cref="WlstCompatibilityValidator.Validate"/> is called before the WLST process
/// is launched.  Any hard violation (e.g. set('Password',...) in a 12c script) aborts the
/// step with a clear error message before any domain files are written.
///
/// Failed artifact retention
/// ─────────────────────────
/// On any WLST failure the generated script, stdout, stderr, and a diagnostic manifest
/// are written to <c>{ReportsDirectory}/failed-wlst/{timestamp}-{sessionId}/</c>.
/// These files are NEVER deleted automatically — they are intended for post-mortem analysis.
/// </summary>
public sealed class CreateDomainStep : IStepExecutor
{
    private readonly IExternalProcessRunner _runner;
    private readonly ILoggingService        _log;

    public CreateDomainStep(IExternalProcessRunner runner, ILoggingService log)
    {
        _runner = runner;
        _log    = log;
    }

    public async Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();

        // ── 1. Resolve WLST launcher ────────────────────────────────────────
        var wlst = WlstDomainScriptBuilder.ResolveWlstCmd(config);
        if (!File.Exists(wlst))
            return StepExecutionResult.Fail(
                $"WLST not found at '{wlst}'. Ensure Fusion Middleware is installed " +
                $"and MiddlewareHome ('{config.Paths.MiddlewareHome}') is correct.",
                retryRecommended: false);

        // ── 2. Generate version-aware script ────────────────────────────────
        //   The factory returns the correct provider for 11g / 12c / 14c / 15c.
        //   The 12c provider uses cmo.setPassword() — the only valid API for 12c+.
        var provider = WlstDomainScriptProviderFactory.Create(config.WebLogicVersion);
        var ctx      = provider.BuildCreateDomainScript(config);

        // ── 3. Structured diagnostic line (always logged, visible in reports) ─
        _log.Info(ctx.ToDiagnosticLine(), "Domain");
        _log.Info(
            $"[WLST] AdminUser={ctx.AdminUser}  " +
            $"RealmPath=/Security/{ctx.TemplateRealmName}/User/{ctx.AdminUser}  " +
            $"PasswordMethod=cmo.setPassword()",
            "Domain");

        // ── 4. Write script to disk BEFORE validation ───────────────────────
        //   Script must be on disk before the validator runs so that RetainFailedArtifacts
        //   can copy it when a validator rejects it.  Pre-validator write also enables
        //   operators to inspect the exact generated Python when the deployment fails
        //   before WLST is ever launched.
        //
        //   A permanent "last generated" debug copy is also written unconditionally so
        //   operators can always find the most recently generated script regardless of
        //   whether a deployment succeeded or failed.
        var scriptPath = Path.Combine(
            config.Paths.TempDirectory, $"wedm_create_domain_{config.Id:N}.py");
        Directory.CreateDirectory(config.Paths.TempDirectory);
        await File.WriteAllTextAsync(scriptPath, ctx.ScriptContent, cancellationToken)
            .ConfigureAwait(false);
        _log.Info($"[WLST] ScriptPath={scriptPath}", "Domain");

        try
        {
            // Permanent debug copy — always overwritten, never cleaned up.
            // Allows post-mortem inspection even for deployments that fail before
            // WLST launches (e.g. when a validator rejects the script).
            var reportsBase = !string.IsNullOrWhiteSpace(config.Paths.ReportsDirectory)
                ? config.Paths.ReportsDirectory
                : Path.Combine(config.Paths.TempDirectory, "reports");
            Directory.CreateDirectory(reportsBase);
            var debugCopy = Path.Combine(reportsBase, "debug-last-generated.py");
            File.Copy(scriptPath, debugCopy, overwrite: true);
            _log.Info($"[WLST] Debug script copy: {debugCopy}", "Domain");
        }
        catch (Exception ex)
        {
            // Non-fatal: debug copy failure must not block the deployment.
            _log.Warning($"[WLST] Debug script copy failed (non-fatal): {ex.Message}", "Domain");
        }

        // ── 5. Pre-execution compatibility validation (fail fast, no JVM) ───
        //   Catches set('Password',...) and other version-incompatible API usage
        //   before WLST starts, before any domain files are written.
        //
        //   NOTE: The validator operates on comment-stripped executable lines only —
        //   Python documentation comments that mention banned patterns must not
        //   trigger false-positive violations.  See WlstCompatibilityValidator.StripCommentLines.
        var compatibility = WlstCompatibilityValidator.Validate(
            ctx.ScriptContent, config.WebLogicVersion);

        foreach (var warning in compatibility.Warnings)
            _log.Warning($"[WLST] Compatibility warning: {warning}", "Domain");

        if (!compatibility.IsCompatible)
        {
            foreach (var violation in compatibility.Violations)
                _log.Error($"[WLST] Compatibility VIOLATION: {violation}", category: "Domain");

            var violationSummary = string.Join(" | ", compatibility.Violations);

            // Script is already on disk (written in step 4) — retain artifacts now.
            RetainFailedArtifacts(config, ctx, scriptPath,
                new ExternalProcessResult(), sw.Elapsed, "ApiCompatibilityValidationFailed");

            return StepExecutionResult.Fail(
                $"WLST script failed compatibility check ({compatibility.Violations.Count} violation(s)). " +
                $"No WLST process was launched. Violations: {violationSummary}",
                retryRecommended: false);
        }

        // ── 5b. Jython syntax pre-flight (fail fast, no JVM started) ────────
        //   Scans the generated Python for constructs that cause a top-level SyntaxError
        //   in Jython 2.2/2.5 (WLS 11g–12c).  The classic offender:
        //     "except Exception as _e:"  →  rejected by Jython with:
        //     "Problem invoking WLST … (no code object) at line 0 … SyntaxError: invalid syntax"
        //   Catching it here produces a clear message before WLST is launched.
        var jythonReport = WlstJythonCompatibilityValidator.Validate(ctx.ScriptContent);

        foreach (var w in jythonReport.Warnings)
            _log.Warning($"[WLST] Jython: {w}", "Domain");

        if (!jythonReport.IsCompatible)
        {
            var violationText = string.Join("\n  ", jythonReport.Violations.Select(v => v.ToString()));
            _log.Error(
                $"[WLST] Jython pre-flight FAILED — {jythonReport.Violations.Count} Python 3 " +
                $"construct(s) found that will cause a SyntaxError at parse time:\n  {violationText}",
                null, "Domain");

            RetainFailedArtifacts(config, ctx, scriptPath,
                new ExternalProcessResult(), sw.Elapsed, "JythonSyntaxValidationFailed");

            return StepExecutionResult.Fail(
                $"Generated WLST script contains Jython-incompatible syntax " +
                $"({jythonReport.Violations.Count} violation(s)):\n{violationText}",
                retryRecommended: false);
        }

        _log.Info($"[WLST] Jython pre-flight: {jythonReport.Summary}", "Domain");

        // ── (script already written in step 4 — log path as confirmation) ────

        // ── 6. Build environment variables ──────────────────────────────────
        var env     = WlstPowerShellEnvironment.FromDeployment(config);
        var envVars = WlstPowerShellEnvironment.BuildEnvironmentVariables(env);
        _log.Info(WlstPowerShellEnvironment.BuildEnvironmentTrace(env), "Domain");

        // ── 7. Launch directly via cmd.exe — no PowerShell wrapper ──────────
        //   cmd.exe /c ""wlst.cmd" "script.py""
        //   The double outer quotes satisfy CMD's /C quoting rule when inner paths
        //   contain spaces:  /c ""C:\path\wlst.cmd" "C:\path\script.py""
        var options = new ExternalProcessOptions
        {
            FileName                  = "cmd.exe",
            Arguments                 = BuildCmdArguments(wlst, scriptPath),
            WorkingDirectory          = config.Paths.TempDirectory,
            EnvironmentVariables      = envVars,
            TotalTimeout              = ExternalProcessTimeouts.DomainCreation,
            SilentProcessTimeout      = ExternalProcessTimeouts.SilentProcess,
            LaunchVerificationTimeout = ExternalProcessTimeouts.LaunchVerification,
            ExpectedChildProcessName  = "java",   // wlst.cmd must spawn the JVM
            Label                     = "WLST CreateDomain",
            EnableWatchdog            = true,
        };

        _log.Info(
            $"[ProcessLaunch] Starting WLST domain creation: cmd.exe {options.Arguments}",
            "Domain");

        var result = await _runner.RunAsync(
            options,
            onStdout: line => _log.ScriptOutput(line),
            onStderr: line => _log.ScriptOutput(line, isError: true),
            cancellationToken: cancellationToken).ConfigureAwait(false);

        sw.Stop();

        // ── 8. Map process result to step result ─────────────────────────────
        if (result.Cancelled)
        {
            RetainFailedArtifacts(config, ctx, scriptPath, result, sw.Elapsed, "Cancelled");
            return StepExecutionResult.Fail("WLST domain creation was cancelled.", -1);
        }

        if (result.TimedOut)
        {
            RetainFailedArtifacts(config, ctx, scriptPath, result, sw.Elapsed, "TimedOut");
            return StepExecutionResult.Fail(
                $"WLST domain creation timed out after {options.TotalTimeout}.", -2);
        }

        if (result.Hung)
        {
            var diagNote = result.Diagnostics is { } d
                ? $" Diagnostics — classification: {d.HangClassification}; "
                + $"last stdout: {d.StdoutTail[..Math.Min(300, d.StdoutTail.Length)]}"
                : string.Empty;
            RetainFailedArtifacts(config, ctx, scriptPath, result, sw.Elapsed, "Hung");
            return StepExecutionResult.Fail(
                $"WLST hung (no process activity for {options.SilentProcessTimeout}).{diagNote}", -3);
        }

        if (result.LaunchFailed)
        {
            RetainFailedArtifacts(config, ctx, scriptPath, result, sw.Elapsed, "LaunchFailed");
            return StepExecutionResult.Fail(
                $"WLST launch failed: {result.LaunchFailureReason}", -4);
        }

        if (result.ExitCode != 0)
        {
            RetainFailedArtifacts(config, ctx, scriptPath, result, sw.Elapsed,
                $"ExitCode={result.ExitCode}");
            return StepExecutionResult.Fail(
                $"WLST failed (exit {result.ExitCode}).\nOutput: {result.Output}\nErrors: {result.Errors}",
                result.ExitCode);
        }

        // ── 9. Verify domain materialised on disk ────────────────────────────
        var domainHome = Path.Combine(config.Paths.DomainBase, config.Domain.DomainName);
        var cfgXml     = Path.Combine(domainHome, "config", "config.xml");
        if (!File.Exists(cfgXml))
        {
            RetainFailedArtifacts(config, ctx, scriptPath, result, sw.Elapsed,
                "DomainNotMaterialised");
            return StepExecutionResult.Fail(
                $"Domain config.xml missing at '{cfgXml}' — WLST reported success " +
                "but produced no domain directory. Check retained WLST artifacts for details.");
        }

        _log.Info($"[WLST] Domain creation complete. config.xml verified at: {cfgXml}", "Domain");
        return StepExecutionResult.Ok($"Domain created at {domainHome}", sw.Elapsed);
    }

    // ── Failed artifact retention ─────────────────────────────────────────────

    /// <summary>
    /// Copies the generated script, stdout, stderr and a diagnostic manifest to
    /// <c>{ReportsDirectory}/failed-wlst/{timestamp}-{configId}/</c>.
    ///
    /// These files are NEVER deleted automatically.  They are intended for post-mortem
    /// analysis: the exact Python script that failed, the WLST output, and all context
    /// needed to reproduce or diagnose the failure.
    ///
    /// The method is best-effort — any I/O error is logged as a warning and does not
    /// affect the step result.
    /// </summary>
    private void RetainFailedArtifacts(
        DeploymentConfiguration config,
        WlstScriptContext ctx,
        string scriptPath,
        ExternalProcessResult result,
        TimeSpan elapsed,
        string failureReason)
    {
        try
        {
            var reportsBase = !string.IsNullOrWhiteSpace(config.Paths.ReportsDirectory)
                ? config.Paths.ReportsDirectory
                : Path.Combine(config.Paths.TempDirectory, "reports");

            var ts         = DateTimeOffset.UtcNow.ToString("yyyyMMdd-HHmmss");
            var retainDir  = Path.Combine(
                reportsBase, "failed-wlst", $"{ts}-{config.Id:N}");
            Directory.CreateDirectory(retainDir);

            // Script (always written; may already be in TempDirectory, copy for isolation)
            var scriptDest = Path.Combine(retainDir, Path.GetFileName(scriptPath));
            if (File.Exists(scriptPath))
                File.Copy(scriptPath, scriptDest, overwrite: true);

            // WLST stdout and stderr
            File.WriteAllText(
                Path.Combine(retainDir, "stdout.txt"),
                result.Output ?? string.Empty);
            File.WriteAllText(
                Path.Combine(retainDir, "stderr.txt"),
                result.Errors ?? string.Empty);

            // Diagnostic manifest — all context for post-mortem
            var manifest = new
            {
                FailureReason       = failureReason,
                WlstDiagnostic      = ctx.ToDiagnosticLine(),
                Version             = ctx.Version.ToString(),
                TemplatePath        = ctx.TemplatePath,
                DomainPath          = ctx.DomainPath,
                AdminUser           = ctx.AdminUser,
                TemplateRealmName   = ctx.TemplateRealmName,
                ScriptGeneratedAt   = ctx.GeneratedAt,
                RetainedAt          = DateTimeOffset.UtcNow.ToString("O"),
                ElapsedSeconds      = elapsed.TotalSeconds,
                ExitCode            = result.ExitCode,
                TimedOut            = result.TimedOut,
                Hung                = result.Hung,
                LaunchFailed        = result.LaunchFailed,
                LaunchFailureReason = result.LaunchFailureReason,
                OriginalScriptPath  = scriptPath,
                ConfigId            = config.Id.ToString("N"),
                ConfigName          = config.Name,
                MachineName         = Environment.MachineName,
            };
            File.WriteAllText(
                Path.Combine(retainDir, "manifest.json"),
                JsonSerializer.Serialize(manifest,
                    new JsonSerializerOptions { WriteIndented = true }));

            _log.Info(
                $"[WLST] Failed artifacts retained at: {retainDir}  " +
                $"(script={scriptDest}  manifest={Path.Combine(retainDir, "manifest.json")})",
                "Domain");
        }
        catch (Exception ex)
        {
            // Non-fatal: artifact retention failure must not mask the real error.
            _log.Warning(
                $"[WLST] Failed to retain artifacts: {ex.Message}  " +
                $"Original script still available at: {scriptPath}",
                "Domain");
        }
    }

    // ── CMD argument construction ─────────────────────────────────────────────

    /// <summary>
    /// Build the CMD /C argument string.  The outer double-quote wrapping is required
    /// by CMD.EXE when the compound command itself contains quoted paths.
    ///   /c ""C:\path with space\wlst.cmd" "C:\path with space\script.py""
    /// </summary>
    private static string BuildCmdArguments(string wlstCmd, string scriptPath)
        => $"/c \"\"{wlstCmd}\" \"{scriptPath}\"\"";
}

/// <summary>Validates AdminServer listen configuration in domain config.xml.</summary>
public sealed class ConfigureAdminServerStep : IStepExecutor
{
    private readonly ILoggingService _log;

    public ConfigureAdminServerStep(ILoggingService log) => _log = log;

    // WebLogic default listen port — config.xml omits <listen-port> when this value is in use.
    // If the element is absent the effective port IS 7001, not an error.
    private const int WlsDefaultListenPort = 7001;

    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();
        var cfgXml = Path.Combine(config.Paths.DomainBase, config.Domain.DomainName, "config", "config.xml");

        _log.Info($"ConfigureAdminServer: checking config.xml at {cfgXml}", "Domain");

        if (!File.Exists(cfgXml))
        {
            sw.Stop();
            return Task.FromResult(StepExecutionResult.Fail(
                $"config.xml not found: {cfgXml}. " +
                "CreateDomain must complete before this step runs."));
        }

        try
        {
            var doc   = XDocument.Load(cfgXml);
            var admin = WebLogicConfigXmlHelper.FindServerByName(doc, config.Domain.AdminServerName);

            if (admin is null)
            {
                // Log server elements found to help diagnose name mismatches.
                var found = doc.Descendants()
                    .Where(e => e.Name.LocalName == "server")
                    .Select(s => WebLogicConfigXmlHelper.ReadChildValue(s, "name") ?? "(unnamed)")
                    .ToList();

                sw.Stop();
                return Task.FromResult(StepExecutionResult.Fail(
                    $"Admin server '{config.Domain.AdminServerName}' not found in config.xml. " +
                    $"Servers present: [{string.Join(", ", found)}]. " +
                    $"Check that AdminServerName in the deployment plan matches the name used in the WLST script."));
            }

            // ── Listen-port verification ─────────────────────────────────────────
            //
            // WebLogic config.xml omits <listen-port> when the port equals the default (7001).
            // Absence of the element does NOT mean the port is unset — it means it is 7001.
            // Treating a missing element as a mismatch was the bug: the step always failed
            // when AdminPort was configured as 7001 even after a perfectly successful writeDomain.
            //
            // Fix: when <listen-port> is absent, effectivePort = WlsDefaultListenPort (7001).
            // Compare effectivePort against the configured port; succeed if they match.

            var rawListenPort = WebLogicConfigXmlHelper.ReadChildValue(admin, "listen-port");
            var rawListenAddr = WebLogicConfigXmlHelper.ReadChildValue(admin, "listen-address");

            bool portElementAbsent = string.IsNullOrEmpty(rawListenPort);
            int  effectivePort     = portElementAbsent
                ? WlsDefaultListenPort
                : (int.TryParse(rawListenPort, out var pp) ? pp : -1);

            _log.Info(
                $"ConfigureAdminServer diagnostics: " +
                $"server='{config.Domain.AdminServerName}' | " +
                $"listen-port element: {(portElementAbsent ? "(absent — WebLogic default)" : rawListenPort)} | " +
                $"effective port: {effectivePort} | " +
                $"configured port: {config.Domain.AdminPort} | " +
                $"listen-address: {rawListenAddr ?? "(absent)"}",
                "Domain");

            if (effectivePort == config.Domain.AdminPort)
            {
                sw.Stop();
                var note = portElementAbsent
                    ? $"AdminServer listen port verified: {effectivePort} " +
                      "(element absent from config.xml — WebLogic omits default port)."
                    : $"AdminServer listen port verified: {effectivePort}.";
                _log.Info(note, "Domain");
                return Task.FromResult(StepExecutionResult.Ok(note, sw.Elapsed));
            }

            sw.Stop();
            return Task.FromResult(StepExecutionResult.Fail(
                $"AdminServer listen port mismatch. " +
                $"config.xml raw <listen-port>: '{rawListenPort ?? "(element absent)"}', " +
                $"effective port: {effectivePort}, " +
                $"configured port (deployment plan): {config.Domain.AdminPort}. " +
                $"If the port element is absent and effective port is {WlsDefaultListenPort} but configured port is {config.Domain.AdminPort}, " +
                $"the WLST script may not have applied set('ListenPort', {config.Domain.AdminPort}) before writeDomain."));
        }
        catch (Exception ex)
        {
            sw.Stop();
            _log.Error(
                $"ConfigureAdminServer: exception while parsing config.xml '{cfgXml}': {ex}", "Domain");
            return Task.FromResult(StepExecutionResult.Fail(
                $"Failed to parse config.xml '{cfgXml}': {ex.GetType().Name}: {ex.Message}", 1, ex));
        }
    }
}

/// <summary>Managed servers are created in the same WLST pass as the domain; this step validates presence.</summary>
public sealed class CreateManagedServersStep : IStepExecutor
{
    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        if (config.Domain.ManagedServers.Count == 0)
            return Task.FromResult(StepExecutionResult.Ok("No managed servers defined — skipped."));

        var cfgXml = Path.Combine(config.Paths.DomainBase, config.Domain.DomainName, "config", "config.xml");
        if (!File.Exists(cfgXml))
            return Task.FromResult(StepExecutionResult.Fail("config.xml missing — domain not created."));

        var doc = XDocument.Load(cfgXml);
        foreach (var ms in config.Domain.ManagedServers)
        {
            if (WebLogicConfigXmlHelper.FindServerByName(doc, ms.Name) is null)
                return Task.FromResult(StepExecutionResult.Fail($"Managed server '{ms.Name}' not found in config.xml."));
        }

        return Task.FromResult(StepExecutionResult.Ok($"Verified {config.Domain.ManagedServers.Count} managed server(s) in config.xml."));
    }
}

/// <summary>Enrols the domain in per-MW nodemanager.domains and ensures domain nodemanager.properties.</summary>
public sealed class ConfigureNodeManagerStep : IStepExecutor
{
    private readonly ILoggingService _log;

    public ConfigureNodeManagerStep(ILoggingService log) => _log = log;

    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();
        var domainHome = Path.Combine(config.Paths.DomainBase, config.Domain.DomainName);
        var nmDir      = Path.Combine(domainHome, "nodemanager");
        Directory.CreateDirectory(nmDir);

        var nmProps = Path.Combine(nmDir, "nodemanager.properties");
        var lines = new List<string>
        {
            "# Generated by WEDM",
            $"ListenPort={config.Domain.NodeManager.Port}",
            $"ListenAddress={config.Domain.NodeManager.ListenAddress}",
            "CrashRecoveryEnabled=true",
            "NativeVersionEnabled=true",
            "DomainsFileRemoteSharingEnabled=false",
            "LogFileCount=10"
        };

        if (string.Equals(config.Domain.NodeManager.Type, "SSL", StringComparison.OrdinalIgnoreCase))
        {
            lines.Add("SecureListener=true");
            lines.Add("AuthenticationProtocol=TLSv1.2");
            lines.Add("# Replace DemoIdentityAndDemoTrust with CustomIdentity/Trust for production keystores");
            lines.Add("KeyStores=DemoIdentityAndDemoTrust");
        }

        if (config.DomainHardening.ProductionMode)
        {
            lines.Add("LogLevel=WARNING");
        }

        var ssl = config.Security.SslCertificates;
        if (!string.IsNullOrWhiteSpace(ssl.IdentityKeystorePath))
        {
            var idPath = Path.GetFullPath(ssl.IdentityKeystorePath);
            lines.Add($"CustomIdentityKeyStoreFileName={idPath}");
            var ext = Path.GetExtension(idPath).ToLowerInvariant();
            lines.Add(ext is ".p12" or ".pfx"
                ? "CustomIdentityKeyStoreType=PKCS12"
                : "CustomIdentityKeyStoreType=JKS");
            if (!string.IsNullOrWhiteSpace(ssl.IdentityPrivateKeyAlias))
                lines.Add($"CustomIdentityAlias={ssl.IdentityPrivateKeyAlias}");
            lines.Add("# CustomIdentityPrivateKeyPassPhrase must be supplied via secure Node Manager startup (not written here).");
        }

        if (!string.IsNullOrWhiteSpace(ssl.TrustKeystorePath))
        {
            var tPath = Path.GetFullPath(ssl.TrustKeystorePath);
            lines.Add($"CustomTrustKeyStoreFileName={tPath}");
            lines.Add("CustomTrustKeyStoreType=PKCS12");
            lines.Add("# CustomTrustKeyStorePassPhrase must be supplied via secure Node Manager startup (not written here).");
        }

        File.WriteAllLines(nmProps, lines);
        _log.Info($"nodemanager.properties written: {nmProps}", "NodeManager");

        var domainsFile = MiddlewareHomePathResolver.ResolveExistingOrDefault(
            MiddlewareHomePathResolver.GetNodeManagerDomainsFileCandidates(config.Paths.MiddlewareHome));
        if (!string.IsNullOrEmpty(domainsFile) && File.Exists(domainsFile))
        {
            var set = new HashSet<string>(File.ReadAllLines(domainsFile).Where(l => !string.IsNullOrWhiteSpace(l)),
                StringComparer.OrdinalIgnoreCase);
            set.Add(domainHome);
            File.WriteAllLines(domainsFile, set.OrderBy(s => s, StringComparer.OrdinalIgnoreCase));
            _log.Info($"Updated nodemanager.domains: {domainsFile}", "NodeManager");
        }
        else
        {
            _log.Warning($"Shared nodemanager.domains not found at '{domainsFile}' — Node Manager may use per-domain files only.", "NodeManager");
        }

        sw.Stop();
        return Task.FromResult(StepExecutionResult.Ok("Node Manager files updated.", sw.Elapsed));
    }
}

public sealed class CreateBootPropertiesStep : IStepExecutor
{
    private readonly ResponseFileGenerator _rsp;
    private readonly ILoggingService      _log;

    public CreateBootPropertiesStep(ResponseFileGenerator rsp, ILoggingService log)
    {
        _rsp = rsp;
        _log = log;
    }

    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(config.Domain.AdminPassword))
            return Task.FromResult(StepExecutionResult.Fail("Admin password is required to generate boot.properties."));

        _rsp.GenerateBootProperties(config, config.Domain.AdminPassword);
        _log.Info("boot.properties generated for Admin and managed servers.", "Security");
        return Task.FromResult(StepExecutionResult.Ok("boot.properties created (will be encrypted on first server start)."));
    }
}

public sealed class ConfigureTnsnamesStep : IStepExecutor
{
    private readonly ResponseFileGenerator _rsp;

    public ConfigureTnsnamesStep(ResponseFileGenerator rsp) => _rsp = rsp;

    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        _rsp.GenerateTnsnames(config);
        return Task.FromResult(StepExecutionResult.Ok("tnsnames.ora written under domain fmwconfig."));
    }
}

public sealed class ConfigureRegistryStep : IStepExecutor
{
    private readonly WindowsRegistryService _registry;
    private readonly ILoggingService        _log;

    public ConfigureRegistryStep(WindowsRegistryService registry, ILoggingService log)
    {
        _registry = registry;
        _log      = log;
    }

    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        var key = "KEY_WEDM_OracleMW";
        _registry.SetOracleHome(key, config.Paths.MiddlewareHome);
        _log.Info($"Oracle registry key {key} → ORACLE_HOME={config.Paths.MiddlewareHome}", "Registry");
        return Task.FromResult(StepExecutionResult.Ok("Oracle ORACLE_HOME registry entry updated."));
    }
}

public sealed class ConfigureFormsEnvStep : IStepExecutor
{
    private readonly ResponseFileGenerator _rsp;
    private readonly ILoggingService       _log;

    public ConfigureFormsEnvStep(ResponseFileGenerator rsp, ILoggingService log)
    {
        _rsp = rsp;
        _log = log;
    }

    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        if (!config.ConfigureFormsReports)
            return Task.FromResult(StepExecutionResult.Ok("Forms configuration disabled — skipped."));

        try
        {
            _rsp.GenerateDefaultEnv(config, Array.Empty<string>());
            return Task.FromResult(StepExecutionResult.Ok("Default.env generated."));
        }
        catch (Exception ex)
        {
            _log.Warning($"Forms Default.env not written: {ex.Message}", "Forms");
            return Task.FromResult(StepExecutionResult.Ok("Forms paths not ready — skipped Default.env."));
        }
    }
}

public sealed class ConfigureWebUtilStep : IStepExecutor
{
    public Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
        => Task.FromResult(StepExecutionResult.Ok("WebUtil deployment is environment-specific — skipped in MVP."));
}

public sealed class RunRcuStep : IStepExecutor
{
    private readonly IRcuAutomationService _rcu;
    private readonly ILoggingService       _log;

    public RunRcuStep(IRcuAutomationService rcu, ILoggingService log)
    {
        _rcu = rcu;
        _log = log;
    }

    public async Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        if (!config.Database.RunRcu)
            return StepExecutionResult.Ok("RCU disabled — skipped.");

        var dryRun = string.Equals(Environment.GetEnvironmentVariable("WEDM_RCU_DRY_RUN"), "1", StringComparison.Ordinal);
        var pre = await _rcu.PrecheckAsync(config, cancellationToken).ConfigureAwait(false);
        if (!pre.CanProceed && !pre.SchemasExist)
            return StepExecutionResult.Fail(string.Join("; ", pre.Messages));

        if (pre.SchemasExist)
        {
            _log.Info($"RCU idempotent skip — schemas exist: {string.Join(", ", pre.ExistingSchemas)}", "RCU");
            return StepExecutionResult.Ok("RCU schemas already present — skipped (no overwrite).");
        }

        var result = await _rcu.ExecuteAsync(config, dryRun, cancellationToken).ConfigureAwait(false);
        if (result.Skipped || result.Success)
            return StepExecutionResult.Ok(result.Output);

        return StepExecutionResult.Fail(result.Error, result.ExitCode);
    }
}

public sealed class PostInstallValidationStep : IStepExecutor
{
    private readonly IValidationEngine _validator;
    private readonly ILoggingService   _log;

    public PostInstallValidationStep(IValidationEngine validator, ILoggingService log)
    {
        _validator = validator;
        _log       = log;
    }

    public async Task<StepExecutionResult> ExecuteAsync(
        DeploymentStep step,
        DeploymentConfiguration config,
        CancellationToken cancellationToken = default)
    {
        var sw = Stopwatch.StartNew();
        var issues = new List<string>();

        if (!Directory.Exists(config.Paths.MiddlewareHome))
            issues.Add($"Middleware home missing: {config.Paths.MiddlewareHome}");

        var invXml = Path.Combine(config.Paths.OracleInventory, "ContentsXML", "inventory.xml");
        if (!File.Exists(invXml))
            issues.Add($"Oracle inventory metadata missing: {invXml}");

        var domainHome = Path.Combine(config.Paths.DomainBase, config.Domain.DomainName);
        if (!File.Exists(Path.Combine(domainHome, "config", "config.xml")))
            issues.Add($"Domain config missing under {domainHome}");

        var nmProps = Path.Combine(domainHome, "nodemanager", "nodemanager.properties");
        if (!File.Exists(nmProps))
            issues.Add("Domain nodemanager.properties missing.");

        var ports = await _validator.ValidatePortsAsync(config, cancellationToken);
        if (!ports.CanProceed)
            issues.Add("One or more required ports are not available.");

        if (issues.Count > 0)
        {
            var msg = string.Join("; ", issues);
            _log.Warning($"Post-install validation: {msg}", "Validation");
            return StepExecutionResult.Fail($"Post-install validation failed: {msg}", 50);
        }

        if (config.RegisterWindowsServices)
        {
            try
            {
                var nmHint = ServiceController.GetServices()
                    .Any(s => s.DisplayName.Contains("Node", StringComparison.OrdinalIgnoreCase) &&
                              s.DisplayName.Contains("Manager", StringComparison.OrdinalIgnoreCase));
                if (!nmHint)
                    _log.Warning("Node Manager Windows service not detected — run installNodeMgrSvc.cmd from WL_HOME\\server\\bin if required.", "Validation");
            }
            catch (Exception ex)
            {
                _log.Warning($"Service probe skipped: {ex.Message}", "Validation");
            }
        }

        sw.Stop();
        return StepExecutionResult.Ok("Post-install validation passed.", sw.Elapsed);
    }
}
